openapi: 3.0.3
info:
  title: 'API#1605 Create/Update Income Savings Submission'
  description: |
    This API allows a customer to update the annual submission provided for an taxable entity's Income Savings.
  version: 0.1.0
  contact:
    name: Andy Coyne
servers:
  - url: 'https://{hostname}:{port}'
    description: Different hostnames and ports are used in different IF environments
    variables:
      hostname:
        default: localhost
        description: 'The hostname for one of IST, Clone, and Production'
      port:
        default: '443'
        description: 'The port for one of IST, Clone, and Production'
tags:
  - name: 'API#1605'
    description: Create/Update Income Savings Submission.
paths:
  '/income-tax/income/savings/{taxableEntityId}/{taxYear}':
    put:
      summary: 'API#1605 Create/Update Income Savings Submission'
      description: >
        This API allows a customer to update the annual submission provided for
        an taxable entity's Income Savings.
        /income-tax/income/savings/{taxableEntityId}/{taxYear} <br>
        /income-tax/income/savings/NW509856B/2019-20

        ```

        Change Log

        ```

          | Version | Date | Author | Description |
          |---|-----|------|-----|
          | 0.1.0 | 22-10-2020 | Andy Coyne | Initial draft |
          

      operationId: createOrUpdateincomeSavings
      tags:
        - 'API#1605'
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/environment'
        - $ref: '#/components/parameters/correlationId'
        - $ref: '#/components/parameters/taxableEntityIdParam'
        - $ref: '#/components/parameters/taxYearParam'
      requestBody:
        required: true
        description: 'API#1605 Create/Update Income Savings Submission Request'
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/requestSchemaAPI1605'
            examples:
              Example1:
                summary: Deductions Submission Request example
                value:
                    securities:
                        taxTakenOff: 0
                        grossAmount: 0
                        netAmount: 0
                    foreignInterest:
                      - countryCode: 'CYM'
                        amountBeforeTax: 0
                        taxTakenOff: 0
                        specialWithholdingTax: 0
                        foreignTaxCreditRelief: true
                        taxableAmount: 0
      responses:
        '204':
          description: 'The request has been accepted, with no content returned.'
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
        '400':
          description: |-
            Bad request
            ```
            A bad request has been made; this could be due to one or more issues with the request
            "code"                              "reason"
            INVALID_TAXABLE_ENTITY_ID           Submission has not passed validation. Invalid parameter taxableEntityId.
            INVALID_TAX_YEAR                    Submission has not passed validation. Invalid parameter taxYear.
            INVALID_PAYLOAD                     Submission has not passed validation. Invalid payload.
            INVALID_CORRELATIONID               Submission has not passed validation. Invalid Header parameter CorrelationId.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Example1_SingleCode:
                  summary: Single Error Code
                  value:
                    failures:
                      - code: INVALID_TAXABLE_ENTITY_ID
                        reason: Submission has not passed validation. Invalid parameter taxableEntityId.
                Example2_MultipleErrorCodes:
                  summary: Multiple Error Codes
                  value:
                    failures:
                      - code: INVALID_PAYLOAD
                        reason: Submission has not passed validation. Invalid payload.
                      - code: INVALID_CORRELATIONID
                        reason: Submission has not passed validation. Invalid Header parameter CorrelationId.
        '500':
          description: |-
            Server Error
            ```
            "code"         "reason"
            SERVER_ERROR   IF is currently experiencing problems that require live service intervention.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Example-ServerError:
                  value:
                    failures:
                      - code: SERVER_ERROR
                        reason: IF is currently experiencing problems that require live service intervention.
        '503':
          description: |-
            Service unavailable
            ```
            "code"                "reason"
            SERVICE_UNAVAILABLE   Dependent systems are currently not responding.
          headers:
            CorrelationId:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse'
              examples:
                Example-ServerUnavailable:
                  value:
                    failures:
                      - code: SERVICE_UNAVAILABLE
                        reason: Dependent systems are currently not responding.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  headers:
    CorrelationId:
      description: CorrelationID - Used for traceability purposes when present
      required: true
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$'
    Content-Type:
      description: Indicates the client what the content type of the returned content actually is
      required: true
      schema:
        type: string
        enum:
          - application/json
  parameters:
    environment:
      in: header
      name: Environment
      description: Mandatory. The environment in use.
      required: true
      schema:
        type: string
        enum:
          - ist0
          - clone
          - live
    correlationId:
      in: header
      name: CorrelationId
      description: Optional. A UUID format string for the transaction. If not specified the IF will create a UUID value to be used
      required: false
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$'
    taxableEntityIdParam:
      in: path
      name: taxableEntityId
      description: Unique identity of the taxable entity
      required: true
      schema:
        type: string
        pattern: '^[a-zA-Z0-9]{1,16}$'
    taxYearParam:
      in: path
      name: taxYear
      description: 'The tax year to which the entity relates. Expects this in the format yyyy-yy, e.g 2019-20 for the 19/20 tax year'
      required: true
      schema:
        type: string
        pattern: '^2[0-9]{3}-[0-9]{2}$'
  schemas:
    errorResponse:
      title: Error Response Schema
      type: object
      additionalProperties: false
      required:
        - failures
      properties:
        failures:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            type: object
            additionalProperties: false
            required:
              - code
              - reason
            properties:
              code:
                description: Keys for all the errors returned
                type: string
                pattern: '^[A-Z0-9_-]{1,160}$'
              reason:
                description: A simple description for the failure
                type: string
                minLength: 1
                maxLength: 160
    requestSchemaAPI1605:
      title: 'API#1605 Create/Update Income Savings Submission Request Schema'
      type: object
      properties:
                securities:
                  type: object
                  properties:
                    taxTakenOff:
                      description: >
                        Defines a monetary value (to 2 decimal places), between
                        _0 and

                        99,999,999,999.99_
                      type: number
                      minimum: 0
                      maximum: 99999999999.99
                      multipleOf: 0.01
                    grossAmount:
                      description: >
                        Defines a monetary value (to 2 decimal places), between
                        _0 and

                        99,999,999,999.99_
                      type: number
                      minimum: 0
                      maximum: 99999999999.99
                      multipleOf: 0.01
                    netAmount:
                      description: >
                        Defines a monetary value (to 2 decimal places), between
                        _0 and

                        99,999,999,999.99_
                      type: number
                      minimum: 0
                      maximum: 99999999999.99
                      multipleOf: 0.01
                  additionalProperties: false
                  minProperties: 1
                  required:
                    - grossAmount
                foreignInterest:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      countryCode:
                        type: string
                        enum:
                          - AFG
                          - ALB
                          - DZA
                          - ASM
                          - AND
                          - AGO
                          - AIA
                          - ATG
                          - ARG
                          - ARM
                          - ABW
                          - AUS
                          - AUT
                          - AZE
                          - BHS
                          - BHR
                          - BGD
                          - BRB
                          - BLR
                          - BEL
                          - BLZ
                          - BEN
                          - BMU
                          - BTN
                          - BOL
                          - BES
                          - BIH
                          - BWA
                          - BRA
                          - VGB
                          - BRN
                          - BGR
                          - BFA
                          - MMR
                          - BDI
                          - KHM
                          - CMR
                          - CAN
                          - CPV
                          - CYM
                          - CAF
                          - TCD
                          - CHL
                          - CHN
                          - CXR
                          - CCK
                          - COL
                          - COM
                          - COG
                          - COK
                          - CRI
                          - CIV
                          - HRV
                          - CUB
                          - CUW
                          - CYP
                          - CZE
                          - COD
                          - DNK
                          - DJI
                          - DMA
                          - DOM
                          - ECU
                          - EGY
                          - SLV
                          - GNQ
                          - ERI
                          - EST
                          - ETH
                          - FLK
                          - FRO
                          - FJI
                          - FIN
                          - FRA
                          - GUF
                          - PYF
                          - GAB
                          - GMB
                          - GEO
                          - DEU
                          - GHA
                          - GIB
                          - GRC
                          - GRL
                          - GRD
                          - GLP
                          - GUM
                          - GTM
                          - GGY
                          - GIN
                          - GNB
                          - GUY
                          - HTI
                          - HND
                          - HKG
                          - HUN
                          - ISL
                          - IND
                          - IDN
                          - IRN
                          - IRQ
                          - IRL
                          - IMN
                          - ISR
                          - ITA
                          - JAM
                          - JPN
                          - JEY
                          - JOR
                          - KAZ
                          - KEN
                          - KIR
                          - XKX
                          - KWT
                          - KGZ
                          - LAO
                          - LVA
                          - LBN
                          - LSO
                          - LBR
                          - LBY
                          - LIE
                          - LTU
                          - LUX
                          - MAC
                          - MKD
                          - MDG
                          - MWI
                          - MYS
                          - MDV
                          - MLI
                          - MLT
                          - MHL
                          - MTQ
                          - MRT
                          - MUS
                          - MYT
                          - MEX
                          - FSM
                          - MDA
                          - MCO
                          - MNG
                          - MNE
                          - MSR
                          - MAR
                          - MOZ
                          - NAM
                          - NRU
                          - NPL
                          - NLD
                          - NCL
                          - NZL
                          - NIC
                          - NER
                          - NGA
                          - NIU
                          - NFK
                          - PRK
                          - MNP
                          - NOR
                          - OMN
                          - PAK
                          - PLW
                          - PAN
                          - PNG
                          - PRY
                          - PER
                          - PHL
                          - PCN
                          - POL
                          - PRT
                          - PRI
                          - QAT
                          - REU
                          - ROU
                          - RUS
                          - RWA
                          - SHN
                          - KNA
                          - LCA
                          - SPM
                          - VCT
                          - WSM
                          - SMR
                          - STP
                          - SAU
                          - SEN
                          - SRB
                          - SYC
                          - SLE
                          - SGP
                          - SXM
                          - SVK
                          - SVN
                          - SLB
                          - SOM
                          - ZAF
                          - KOR
                          - SSD
                          - ESP
                          - LKA
                          - SDN
                          - SUR
                          - SJM
                          - SWZ
                          - SWE
                          - CHE
                          - SYR
                          - TWN
                          - TJK
                          - TZA
                          - THA
                          - TLS
                          - TGO
                          - TKL
                          - TON
                          - TTO
                          - TUN
                          - TUR
                          - TKM
                          - TCA
                          - TUV
                          - UGA
                          - UKR
                          - ARE
                          - USA
                          - VIR
                          - URY
                          - UZB
                          - VUT
                          - VAT
                          - VEN
                          - VNM
                          - WLF
                          - YEM
                          - ZMB
                          - ZWE
                          - ZZZ
                        example: CYM
                      amountBeforeTax:
                        description: >
                          Defines a monetary value (to 2 decimal places),
                          between _0 and

                          99,999,999,999.99_
                        type: number
                        minimum: 0
                        maximum: 99999999999.99
                        multipleOf: 0.01
                      taxTakenOff:
                        description: >
                          Defines a monetary value (to 2 decimal places),
                          between _0 and

                          99,999,999,999.99_
                        type: number
                        minimum: 0
                        maximum: 99999999999.99
                        multipleOf: 0.01
                      specialWithholdingTax:
                        description: >
                          Defines a monetary value (to 2 decimal places),
                          between _0 and

                          99,999,999,999.99_
                        type: number
                        minimum: 0
                        maximum: 99999999999.99
                        multipleOf: 0.01
                      foreignTaxCreditRelief:
                        type: boolean
                      taxableAmount:
                        description: >
                          Defines a monetary value (to 2 decimal places),
                          between _0 and

                          99,999,999,999.99_
                        type: number
                        minimum: 0
                        maximum: 99999999999.99
                        multipleOf: 0.01
                    additionalProperties: false
                    minProperties: 1
                    required:
                      - countryCode
                      - taxableAmount
      additionalProperties: false
      minProperties: 1